import { ApolloProvider } from '@apollo/client';
import { ChakraProvider } from '@chakra-ui/react';
import { Provider } from 'next-auth/client';
import Head from 'next/head';
import '../styles/globals.scss';
import apolloClient from '../lib/apollo';

export default function MyApp({ Component, pageProps }) {
  return (
    <Provider session={pageProps.session}>
      <ApolloProvider client={apolloClient}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='initial-scale=1, width=device-width' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <ChakraProvider>
          <Component {...pageProps} />
        </ChakraProvider>
      </ApolloProvider>
    </Provider>
  );
}
