import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { gql, useQuery } from '@apollo/client'
import Sidebar from '../components/Sidebar'

const FetchProjectsQuery = gql`
  query FetchProjects($userId: Int!) {
    projects(userId: $userId) {
      id
      name
    }
  }
`

export default function Home() {
  const { data, loading, error } = useQuery(FetchProjectsQuery, {
    variables: { userId: 1 },
  });

  if (loading) return <p>Loading...</p>
  if (error) return <p>Oh no... {error.message}</p>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sidebar></Sidebar>
        <ul>
          {data.projects.map(project => (
            <li key={project.id}>
              <p>{project.name}</p>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}
